[package]
name = "packtab-macro"
version = "0.4.0"
edition = "2021"
description = "Proc-macro for packtab compile-time table generation"
license = "Apache-2.0"
repository = "https://github.com/behdad/packtab.rs"

[lib]
proc-macro = true

[dependencies]
packtab = { version = "0.4.0", path = "../packtab" }
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
