[package]
name = "packtab-icu4x"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
icu_collections = { path = "/Users/behdad/icu4x/components/collections" }
icu_properties = { path = "/Users/behdad/icu4x/components/properties", default-features = false }
packtab = { path = "../packtab" }

[dev-dependencies]
icu_codepointtrie_builder = { path = "/Users/behdad/icu4x/components/collections/codepointtrie_builder" }
tempfile = "3"
