[package]
name = "packtab-icu4x"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[features]
default = []
compiled_data = ["icu_properties/compiled_data"]

[dependencies]
icu_collections = { path = "/Users/behdad/icu4x/components/collections" }
icu_properties = { path = "/Users/behdad/icu4x/components/properties", default-features = false }
packtab = { path = "../packtab" }

[dev-dependencies]
criterion = "0.5.0"
icu_codepointtrie_builder = { path = "/Users/behdad/icu4x/components/collections/codepointtrie_builder" }
tempfile = "3"

[build-dependencies]
icu_collections = { path = "/Users/behdad/icu4x/components/collections" }
icu_properties = { path = "/Users/behdad/icu4x/components/properties", default-features = false, features = ["compiled_data"] }
packtab = { path = "../packtab" }

[[bin]]
name = "packtab-icu4x-gen"
path = "src/bin/packtab-icu4x-gen.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-gc-icu"
path = "src/bin/size-gc-icu.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-gc-packtab"
path = "src/bin/size-gc-packtab.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-gc-packtab-unsafe"
path = "src/bin/size-gc-packtab-unsafe.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-gc-packtab-c5"
path = "src/bin/size-gc-packtab-c5.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-gc-packtab-c5-unsafe"
path = "src/bin/size-gc-packtab-c5-unsafe.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-gc-packtab-c9"
path = "src/bin/size-gc-packtab-c9.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-gc-packtab-c9-unsafe"
path = "src/bin/size-gc-packtab-c9-unsafe.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-script-icu"
path = "src/bin/size-script-icu.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-script-packtab"
path = "src/bin/size-script-packtab.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-script-packtab-unsafe"
path = "src/bin/size-script-packtab-unsafe.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-script-packtab-c5"
path = "src/bin/size-script-packtab-c5.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-script-packtab-c5-unsafe"
path = "src/bin/size-script-packtab-c5-unsafe.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-script-packtab-c9"
path = "src/bin/size-script-packtab-c9.rs"
required-features = ["compiled_data"]

[[bin]]
name = "size-script-packtab-c9-unsafe"
path = "src/bin/size-script-packtab-c9-unsafe.rs"
required-features = ["compiled_data"]

[[bench]]
name = "properties"
harness = false
required-features = ["compiled_data"]
