[package]
name = "packtab-cli"
version = "0.2.0"
edition = "2021"
description = "CLI for packtab table packing"
license = "Apache-2.0"
repository = "https://github.com/behdad/packtab.rs"

[[bin]]
name = "packtab"
path = "src/main.rs"

[dependencies]
packtab = { version = "0.2.0", path = "../packtab" }
clap = { version = "4", features = ["derive"] }
